# Generated by Django 5.2 on 2025-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.TextField(blank=True, max_length=254, null=True)),
                ('Patient_name', models.CharField(blank=True, max_length=254, null=True)),
                ('Date', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
