# Generated by Django 5.1.3 on 2025-04-16 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_department_doctors_appoinment_massage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.department'),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='Date',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='Phone',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
